In [2]:
!pip install gensim

In [1]:
!pip install numpy==1.25.2

In [3]:
import gensim

In [4]:
from gensim.models import Word2Vec, KeyedVectors

In [5]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')
vec_king = wv['king']

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [6]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [7]:
vec_king.shape

(300,)

In [8]:
wv['happy']

array([-5.18798828e-04,  1.60156250e-01,  1.60980225e-03,  2.53906250e-02,
        9.91210938e-02, -8.59375000e-02,  3.24218750e-01, -2.17285156e-02,
        1.34765625e-01,  1.10351562e-01, -1.04980469e-01, -2.90527344e-02,
       -2.38037109e-02, -4.02832031e-02, -3.68652344e-02,  2.32421875e-01,
        3.20312500e-01,  1.01074219e-01,  5.83496094e-02, -2.91824341e-04,
       -3.29589844e-02,  2.11914062e-01,  4.32128906e-02, -8.59375000e-02,
        2.81250000e-01, -1.78222656e-02,  3.79943848e-03, -1.71875000e-01,
        2.06054688e-01, -1.85546875e-01,  3.73535156e-02, -1.21459961e-02,
        2.04101562e-01, -3.80859375e-02,  3.61328125e-02, -8.15429688e-02,
        8.44726562e-02,  9.37500000e-02,  1.44531250e-01,  7.42187500e-02,
        2.51953125e-01, -7.91015625e-02,  8.69140625e-02,  1.58691406e-02,
        1.09375000e-01, -2.23632812e-01, -5.15747070e-03,  1.68945312e-01,
       -1.36718750e-01, -2.51464844e-02, -3.85742188e-02, -1.33056641e-02,
        1.38671875e-01,  

In [11]:
wv.most_similar('confident')

[('optimistic', 0.7304733395576477),
 ('hopeful', 0.7214711904525757),
 ('cautiously_optimistic', 0.6931204795837402),
 ('convinced', 0.632867157459259),
 ('satisfied', 0.6151667237281799),
 ('supremely_confident', 0.61335688829422),
 ('pleased', 0.6058984398841858),
 ('confi_dent', 0.5978137850761414),
 ('happy', 0.589353084564209),
 ('guardedly_optimistic', 0.5835862159729004)]

In [12]:
wv.similarity('man','woman')

0.76640123

In [13]:
vec = wv['human']-wv['man']+wv['animal']

In [14]:
vec

array([-2.62145996e-01,  1.66503906e-01, -9.66796875e-02,  4.84375000e-01,
       -4.48730469e-01,  9.02099609e-02,  7.83203125e-01, -7.69653320e-02,
       -3.41796875e-01, -2.09884644e-02, -4.10156250e-02, -2.75146484e-01,
       -2.84179688e-01, -2.17773438e-01, -2.66845703e-01,  7.44628906e-02,
       -1.75048828e-01,  2.52685547e-01, -1.81396484e-01,  1.97021484e-01,
        5.46875000e-02, -5.45242310e-01,  1.69189453e-01,  2.78808594e-01,
       -1.67480469e-01, -3.25927734e-02, -3.98437500e-01,  1.61132812e-01,
        1.89453125e-01, -3.26660156e-01, -5.82031250e-01, -2.97851562e-01,
       -2.91503906e-01, -2.31323242e-01, -4.41406250e-01, -1.46484375e-03,
       -3.22265625e-01,  2.37304688e-01,  9.91210938e-02,  6.34765625e-02,
       -2.36816406e-02,  3.43261719e-01, -5.30761719e-01,  5.88195801e-01,
       -6.65039062e-01, -7.37304688e-02,  3.61328125e-01,  6.08642578e-01,
        2.99804688e-01,  1.62109375e-01,  1.84875488e-01, -3.98437500e-01,
       -1.19873047e-01,  

In [15]:
wv.most_similar([vec])

[('animal', 0.785584568977356),
 ('human', 0.7484273910522461),
 ('animals', 0.6385680437088013),
 ('animal_welfare', 0.5512871742248535),
 ('Animal', 0.5368677377700806),
 ('nonhuman_animals', 0.5150101184844971),
 ('humans', 0.5113890171051025),
 ('nonhumans', 0.510823667049408),
 ('zoos_circuses', 0.5015814304351807),
 ('equine', 0.4981248080730438)]